spring:
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/testDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000